/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Dao.GPAdao;
import Dao.Studentdao;
import Model.GPAclass;
import Model.People;
import helper.DataValidator;
import helper.MessageDialog;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.table.DefaultTableModel;
import Dao.Peopledao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
/**
 *
 * @author LENOVO
 */
public class GPA extends javax.swing.JPanel {
    private DefaultTableModel tbModel1;
    /**
     * Creates new form GPA
     */
    public GPA() {
        initComponents();
        initTable();
        loadgpa();
    }
    private void initTable(){
        tbModel1 = new DefaultTableModel();
        tbModel1.setColumnIdentifiers(new String[]{"MSSV","Lập trình hướng đối tượng","Xử lý ảnh"
        ,"Xử lý tín hiệu số","Thực hành thiết kế SOC","Điểm trung bình"});
        tbgpa.setModel(tbModel1);
    
    }
    private void loadgpa(){
        try { 
             GPAdao dao = new GPAdao();
            ArrayList<GPAclass> list = dao.findtopby(1);
            tbModel1.setRowCount(0);
            for (GPAclass g :list){
                tbModel1.addRow(new Object[]{g.getMssv(),g.getOOP(),g.getImageP(),g.getPSD(),g.getSOC(),
                ( g.getOOP() + g.getImageP() + g.getPSD() + g.getSOC() )/4
            
            });
            }
            tbModel1.fireTableDataChanged();
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(jPanel1, e.getMessage(), "Lỗi");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmssv1 = new javax.swing.JTextField();
        txtoop = new javax.swing.JTextField();
        txtim = new javax.swing.JTextField();
        txtpsd = new javax.swing.JTextField();
        txtsoc = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbgpa = new javax.swing.JLabel();
        btnavg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbgpa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("MSSV");

        jLabel3.setText("Lập trình hướng đối tượng");

        jLabel4.setText("Xử lý ảnh");

        jLabel5.setText("Xử lý tín hiệu số");

        jLabel6.setText("Thực hành thiết kế SOC");

        txtmssv1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmssv1FocusLost(evt);
            }
        });

        txtoop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoopFocusLost(evt);
            }
        });
        txtoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoopActionPerformed(evt);
            }
        });

        txtim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoopFocusLost(evt);
            }
        });
        txtim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimActionPerformed(evt);
            }
        });

        txtpsd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoopFocusLost(evt);
            }
        });
        txtpsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpsdActionPerformed(evt);
            }
        });

        txtsoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoopFocusLost(evt);
            }
        });
        txtsoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsocActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 204, 255));
        btnsave.setText("Lưu");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 204, 255));
        btnupdate.setText("Cập nhật");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnnew.setBackground(new java.awt.Color(255, 255, 153));
        btnnew.setText("Tạo mới");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 51, 153));
        btndelete.setText("Xoá");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(0, 204, 255));
        btnsearch.setText("Tìm kiếm");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpsd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnnew))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnsearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnsave)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate)))
                        .addGap(18, 18, 18)
                        .addComponent(btndelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtim)
                            .addComponent(txtmssv1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtoop)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmssv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addComponent(btnnew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnsearch))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("Điểm TB");

        lbgpa.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lbgpa.setForeground(new java.awt.Color(0, 204, 255));
        lbgpa.setText("0.00");

        btnavg.setBackground(new java.awt.Color(0, 204, 255));
        btnavg.setText("AVG");
        btnavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnavg))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbgpa)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnavg)
                .addContainerGap())
        );

        tbgpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbgpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbgpaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbgpa);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoopActionPerformed

    private void txtimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        txtoop.setText("");
        txtpsd.setText("");
        txtim.setText("");
        txtsoc.setText("");
        txtmssv1.setText("");
        txtname.setText("");
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       StringBuilder sb = new StringBuilder();
       DataValidator.validateEmty(txtmssv1, sb, "Nhập mssv");
       DataValidator.validateEmty(txtsoc, sb, "Nhập điểm môn soc");
       if(sb.length()>0){
           MessageDialog.showErrorDialog(jPanel2, sb.toString(), "Lỗi");
           return;
       }
        try {
            GPAclass gp = new GPAclass();
            gp.setMssv(txtmssv1.getText());
            gp.setOOP(Float.parseFloat(txtoop.getText()));
            gp.setImageP(Float.parseFloat(txtim.getText()));
            gp.setPSD(Float.parseFloat(txtpsd.getText()));
            gp.setSOC(Float.parseFloat(txtsoc.getText()));
            GPAdao dao = new GPAdao();
            if(dao.findby(txtmssv1.getText()) !=null){
                if (MessageDialog.showConfirmDialog(jPanel2,"Bạn có muốn cập nhật lại điểm không","Hỏi")==JOptionPane.NO_OPTION){
                    return;
                }
                if(dao.update(gp)){
                MessageDialog.showMessageDialog(jPanel2, "Đã cập nhật","Thông báo");
            }
                else{
                 MessageDialog.showMessageDialog(jPanel2, "Không cập nhật được","Lỗi");
            }}
            else{
                if(dao.insert(gp)){
                    MessageDialog.showMessageDialog(jPanel2, "Đã lưu","Thông báo");
                }
                else{
                     MessageDialog.showMessageDialog(jPanel2, "Không lưu được","Lỗi");
                }
            }
            loadgpa();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(jPanel2, e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtsocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsocActionPerformed

    private void txtpsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpsdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpsdActionPerformed

    private void txtmssv1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmssv1FocusLost
        try {
            Studentdao dao = new Studentdao();
            People.SV sv =dao.findby(txtmssv1.getText());
            if( sv != null){
                txtname.setText(sv.getName());
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_txtmssv1FocusLost

    private void txtoopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoopFocusLost
        if ((txtoop.getText().equals(""))||(txtpsd.getText().equals(""))||(txtim.getText().equals(""))||(txtsoc.getText().equals(""))){
            return;
        }
               
        float oop = Float.parseFloat(txtoop.getText());
        float psd = Float.parseFloat(txtpsd.getText());
        float im = Float.parseFloat(txtim.getText());
        float soc = Float.parseFloat(txtsoc.getText());
        
        float avg = (oop + psd + im + soc)/4;
        String st;
        st = String.format("%.2f", avg);
        lbgpa.setText(st);
    }//GEN-LAST:event_txtoopFocusLost

    private void btnavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavgActionPerformed
       if ((txtoop.getText().equals(""))||(txtpsd.getText().equals(""))||(txtim.getText().equals(""))||(txtsoc.getText().equals(""))){
            return;
        }
               
        float oop = Float.parseFloat(txtoop.getText());
        float psd = Float.parseFloat(txtpsd.getText());
        float im = Float.parseFloat(txtim.getText());
        float soc = Float.parseFloat(txtsoc.getText());
        
        float avg = (oop + psd + im + soc)/4;
        String st;
        st = String.format("%.2f", avg);
        lbgpa.setText(st);
    }//GEN-LAST:event_btnavgActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            GPAdao dao = new GPAdao();
            GPAclass gp = dao.findby(txtmssv1.getText());
            if( gp != null){
                txtim.setText(String.format("%.2f", gp.getImageP()));
                txtoop.setText(String.format("%.2f", gp.getOOP()));
                txtpsd.setText(String.format("%.2f", gp.getPSD()));
                txtsoc.setText(String.format("%.2f", gp.getSOC()));
                txtoopFocusLost(null);
                txtmssv1FocusLost(null);
            }
            else{
                MessageDialog.showMessageDialog(jPanel1,"Không tìm thấy SV","Thông báo");
            }
            loadgpa();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        btnsaveActionPerformed(null);
        loadgpa();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            if(txtmssv1.getText().equals("")){
                 MessageDialog.showMessageDialog(jPanel1, "Nhập MSSV","Lỗi");
                 return;
            }
            GPAdao dao = new GPAdao();
            GPAclass gp = dao.findby(txtmssv1.getText());
            if(gp == null){
                MessageDialog.showMessageDialog(jPanel1, "SV không tồn tại","Lỗi");
                return;
            }
            if(MessageDialog.showConfirmDialog(jPanel1, "Bạn có muốn xoá thông tin không?","Hỏi")==JOptionPane.NO_OPTION){
                return;
            }
            if(dao.deleteby(txtmssv1.getText())){
                MessageDialog.showMessageDialog(jPanel1, "Điểm của SV đã được xoá","Thông báo");
                
            }
            else{
                MessageDialog.showMessageDialog(jPanel1, "Điểm của sinh viên không xoá được","Lỗi");
            
            }
            
            loadgpa();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showMessageDialog(jPanel1, e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tbgpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbgpaMouseClicked
        try {
            int row = tbgpa.getSelectedRow();
            if(row>=0){
                String mssv =(String) tbgpa.getValueAt(row, 0);
                GPAdao dao = new GPAdao();
                GPAclass gp = dao.findby(mssv);
                if(gp != null){
                    txtmssv1.setText(gp.getMssv());
                    //
                    txtoop.setText(Float.toString(gp.getOOP()));
                    txtpsd.setText(Float.toString(gp.getPSD()));
                    txtim.setText(Float.toString(gp.getImageP()));
                    txtsoc.setText(Float.toString(gp.getSOC()));
                    
                
                
                
                }
            }
            txtmssv1FocusLost(null);
            txtoopFocusLost(null);
           
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(this, e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_tbgpaMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnavg;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbgpa;
    private javax.swing.JTable tbgpa;
    private javax.swing.JTextField txtim;
    private javax.swing.JTextField txtmssv1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtoop;
    private javax.swing.JTextField txtpsd;
    private javax.swing.JTextField txtsoc;
    // End of variables declaration//GEN-END:variables
}
