/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class MainForm extends javax.swing.JFrame {
    private StudentManagement mManageSV;
    private GPA mGPA;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menulogout = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ManageSV = new javax.swing.JMenuItem();
        ManageGPA = new javax.swing.JMenuItem();
        menunote1 = new javax.swing.JMenu();
        menuabout = new javax.swing.JMenuItem();
        menuchat = new javax.swing.JMenuItem();
        menunote = new javax.swing.JMenuItem();
        smail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabMain.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Hệ thống");

        menulogout.setText("Logout");
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menulogout);

        jMenuItem1.setText("Demo");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        ManageSV.setText("Thông tin sinh viên");
        ManageSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSVActionPerformed(evt);
            }
        });
        jMenu2.add(ManageSV);

        ManageGPA.setText("Kết quả học tập");
        ManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageGPAActionPerformed(evt);
            }
        });
        jMenu2.add(ManageGPA);

        jMenuBar1.add(jMenu2);

        menunote1.setText("Trợ giúp");
        menunote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunote1ActionPerformed(evt);
            }
        });

        menuabout.setText("Giới thiệu");
        menuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaboutActionPerformed(evt);
            }
        });
        menunote1.add(menuabout);

        menuchat.setText("Chat");
        menuchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuchatActionPerformed(evt);
            }
        });
        menunote1.add(menuchat);

        menunote.setText("Note");
        menunote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunoteActionPerformed(evt);
            }
        });
        menunote1.add(menunote);

        smail.setText("Gửi mail");
        smail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smailActionPerformed(evt);
            }
        });
        menunote1.add(smail);

        jMenuBar1.add(menunote1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed
        Loginnew nw = new Loginnew(this, true);
        nw.setVisible(true);
        
    }//GEN-LAST:event_menulogoutActionPerformed

    private void ManageSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSVActionPerformed
        if(mManageSV == null){
        mManageSV = new StudentManagement();
        ImageIcon icon = new ImageIcon(getClass().getResource("/IMG/sv.png"));
        tabMain.addTab("Quản lý sinh viên",icon,mManageSV,"Quản lý sinh viên");
      }
      tabMain.setSelectedComponent(mManageSV);
         
    }//GEN-LAST:event_ManageSVActionPerformed

    private void ManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageGPAActionPerformed
       if(mGPA == null){
        mGPA = new GPA();
        ImageIcon icon = new ImageIcon(getClass().getResource("/IMG/round_insights_black_24dp.png"));
        tabMain.addTab("Kết quả học tập",icon,mGPA,"Kết quả học tập");
      }
      tabMain.setSelectedComponent(mGPA); 
    }//GEN-LAST:event_ManageGPAActionPerformed

    private void menuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaboutActionPerformed
      about a;
      a = new about(this, true);
      a.setVisible(true);
    }//GEN-LAST:event_menuaboutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void menuchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuchatActionPerformed
       
     chat c = new chat(this, true);
     c.setVisible(true);
    }//GEN-LAST:event_menuchatActionPerformed

    private void menunote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunote1ActionPerformed
        
    }//GEN-LAST:event_menunote1ActionPerformed

    private void menunoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunoteActionPerformed
        
       Noteui n = new Noteui(this, true);
       n.setVisible(true);
    }//GEN-LAST:event_menunoteActionPerformed

    private void smailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smailActionPerformed
        MAIL m = new MAIL(this, true);
        m.setVisible(true);
    }//GEN-LAST:event_smailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ManageGPA;
    private javax.swing.JMenuItem ManageSV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuabout;
    private javax.swing.JMenuItem menuchat;
    private javax.swing.JMenuItem menulogout;
    private javax.swing.JMenuItem menunote;
    private javax.swing.JMenu menunote1;
    private javax.swing.JMenuItem smail;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
