/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import helper.MessageDialog;
import helper.DataValidator;
import helper.ConnectDB;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Model.People.SV;
import Model.People;
import Dao.Peopledao;
import Dao.Studentdao;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import java.util.ArrayList;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class StudentManagement extends javax.swing.JPanel {
    private MainForm parentFrom;
    private DefaultTableModel tbModel;
    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
        initTable();
        loadData();
    }
    private void initTable(){
        tbModel = new DefaultTableModel();
        tbModel.setColumnIdentifiers(new String[]{"MSSV","Họ tên","Ngày tháng năm sinh","SĐT","Địa chỉ","CMND","Giới tính"});
        tablestudent.setModel(tbModel);
    }
    private void loadData(){
        try { 
            Studentdao dao = new Studentdao();
            ArrayList<People.SV> list = dao.findallby();
            tbModel.setRowCount(0);
            for (People.SV it :list){
                tbModel.addRow(new Object[]{
                it.getMssv(),it.getName(),it.getbirthDate(),it.getphone(),it.getaddress(),it.getid(),it.getsex()
            
            });
            }
            tbModel.fireTableDataChanged();
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(), "Lỗi");
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        txtmssv1 = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablestudent = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsex = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnsx = new javax.swing.JButton();
        txtphone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtmssv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmssv1ActionPerformed(evt);
            }
        });

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 204, 255));
        btnsave.setText("Lưu");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 204, 255));
        btnupdate.setText("Cập nhật");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnnew.setBackground(new java.awt.Color(0, 204, 255));
        btnnew.setText("Tạo");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("MSSV");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Địa chỉ");

        tablestudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablestudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablestudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablestudent);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("CMND");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Ngày sinh");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Giới tính");

        txtsex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnsx.setBackground(new java.awt.Color(102, 255, 204));
        btnsx.setText("Sắp xếp");
        btnsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsx))
        );

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Số điện thoại");

        btndelete.setBackground(new java.awt.Color(255, 51, 153));
        btndelete.setText("Xoá");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtaddress)
                            .addComponent(txtdate)
                            .addComponent(txtmssv1)
                            .addComponent(txtname)
                            .addComponent(txtid)
                            .addComponent(txtsex, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndelete)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtmssv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btnnew)
                            .addComponent(btnupdate)
                            .addComponent(btndelete)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmssv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmssv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmssv1ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        txtname.setText("");
        txtphone.setText("");
        txtaddress.setText("");
        txtid.setText("");
        txtdate.setText("");
        txtsex.getItemAt(0);
        txtmssv1.setText("");
        
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        StringBuilder sb = new StringBuilder();
        
        DataValidator.validateEmty(txtname, sb, "Hãy nhập tên sinh viên");
        if(sb.length()>0){
            MessageDialog.showErrorDialog(parentFrom, sb.toString(),"Lỗi");
            return;
        
        }
        if(MessageDialog.showConfirmDialog(parentFrom, "Bạn có muốn cập nhật không","Hỏi")== JOptionPane.NO_OPTION){
            return;
        }
        
        try {
            People s = new  People();
            SV sv = s.new SV();
            sv.setMssv(txtmssv1.getText());
            sv.setName(txtname.getText());
            sv.setaddress(txtaddress.getText());
            sv.setid(Integer.parseInt(txtid.getText()));
            sv.setphone(Integer.parseInt(txtphone.getText()));
            sv.setsex((String) txtsex.getSelectedItem());
            
            try {
            sv.setbirthDate(new SimpleDateFormat("dd-MM-yyyy").parse(txtdate.getText()));
         
                }
          
            catch(ParseException ex){
                MessageDialog.showErrorDialog(parentFrom,ex.getMessage(),"You type wrong format date/n Bạn đã nhập sai định dạng ngày tháng");
                ex.printStackTrace();
                                    }
           Studentdao dao = new Studentdao();
            if(dao.update(sv)){
                MessageDialog.showMessageDialog(parentFrom, "Thông tin đã được cập nhật","Thông báo");
                loadData();
            }
            else{
                MessageDialog.showMessageDialog(parentFrom, "Thông tin chưa được cập nhật","Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(),"Error");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        StringBuilder sb = new StringBuilder();
        
        DataValidator.validateEmty(txtname, sb, "Hãy tên sinh viên");
        if(sb.length()>0){
            MessageDialog.showErrorDialog(parentFrom, sb.toString(),"Lỗi");
            return;
        
        }
        try {
            People s = new  People();
            SV sv = s.new SV();
            sv.setMssv(txtmssv1.getText());
            sv.setName(txtname.getText());
            sv.setaddress(txtaddress.getText());
            sv.setid(Integer.parseInt(txtid.getText()));
            sv.setphone(Integer.parseInt(txtphone.getText()));
            sv.setsex((String) txtsex.getSelectedItem());
            
            try {
            sv.setbirthDate(new SimpleDateFormat("dd-MM-yyyy").parse(txtdate.getText()));
         
                }
          
            catch(ParseException ex){
                MessageDialog.showErrorDialog(parentFrom,ex.getMessage(),"You type wrong format date/n Bạn đã nhập sai định dạng ngày tháng");
                ex.printStackTrace();
                                    }
           Studentdao dao = new Studentdao();
            if(dao.insert(sv)){
                MessageDialog.showMessageDialog(parentFrom, "Thông tin đã được lưu","Thông báo");
                loadData();
            }
            else{
                MessageDialog.showMessageDialog(parentFrom, "Thông tin chưa được lưu","Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(),"Error");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        StringBuilder sb = new StringBuilder();
        
        DataValidator.validateEmty(txtmssv1, sb, "Hãy nhập mã số sinh viên");
        if(sb.length()>0){
            MessageDialog.showErrorDialog(parentFrom, sb.toString(),"Lỗi");
            return;
        
        }
        if(MessageDialog.showConfirmDialog(parentFrom, "Bạn có muốn xoá sinh viên này hay không","Hỏi")== JOptionPane.NO_OPTION){
            return;
        }
        
        try {
            People s = new  People();
            SV sv = s.new SV();
           Studentdao dao = new Studentdao();
            if(dao.delete(txtmssv1.getText())){
                MessageDialog.showMessageDialog(parentFrom, "Thông tin đã được xoá","Thông báo");
                loadData();
            }
            else{
                MessageDialog.showMessageDialog(parentFrom, "Thông tin chưa được xoá","Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(),"Error");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tablestudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablestudentMouseClicked
        try {
            int row = tablestudent.getSelectedRow();
            if(row>=0){
                String mssv =(String) tablestudent.getValueAt(row, 0);
                Studentdao dao = new Studentdao();
                People.SV sv = dao.findby(mssv);
                if(sv != null){
                    txtmssv1.setText(sv.getMssv());
                    txtname.setText(sv.getName());
                    txtaddress.setText(sv.getaddress());
                    txtphone.setText(Integer.toString(sv.getphone()));
                    txtid.setText(Integer.toString(sv.getid()));
                    txtdate.setText(new SimpleDateFormat("dd-MM-yyyy").format(sv.getbirthDate())); //convert String to date.
                    txtsex.setSelectedItem(sv.getsex());
                
                
                
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(),"Lỗi");
        }
    }//GEN-LAST:event_tablestudentMouseClicked

    private void btnsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsxActionPerformed
       try { 
            Studentdao dao = new Studentdao();
            ArrayList<People.SV> list = dao.sapxep();
            tbModel.setRowCount(0);
            for (People.SV it :list){
                tbModel.addRow(new Object[]{
                it.getMssv(),it.getName(),it.getbirthDate(),it.getphone(),it.getaddress(),it.getid(),it.getsex()
            
            });
            }
            tbModel.fireTableDataChanged();
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentFrom, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnsxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsx;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tablestudent;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmssv1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JComboBox<String> txtsex;
    // End of variables declaration//GEN-END:variables
}
